#!/bin/bash
WORD2VECCMD=$(type -ap word2vec)
if [ -n "${WORD2VECCMD}" ]; then
    WORD2VECCMD=${FOUND}
else
    WORD2VECDIR='external/word2vec/'
    WORD2VECCMD=$WORD2VECDIR'word2vec'
    if [ ! -x "${WORD2VECCMD}" ]; then
        CURRENTDIR=$(pwd)
        cd $WORD2VECDIR
        if [ $? -ne 0 ]; then
            echo 'Error: Failed to go into '$WORD2VECDIR'! Is the submodule missing?'
            exit
        fi
        make word2vec
        if [ $? -ne 0 ]; then
            echo 'Error: Failed to make word2vec!'
            exit
        fi
        cd $CURRENTDIR
    fi
fi

if [ -z "${WORD2VECCMD}" ]; then
    echo 'Error: Cannot find word2vec!'
    exit
fi

th generatecorpus.lua -datadir dataset -outfile corpus.txt
$WORD2VECCMD -train dataset/corpus.txt -output dataset/embeddings.txt -size 10 -window 5 -negative 20 -iter 30 -min-count 1
th convertembedding.lua -datadir dataset -outfile embeddings.t7
